# theme: jekyll-theme-leap-day
# Site settings
title: 华美如玉                 #你博客的标题
SEOTitle: 华美如玉 | Adrian Wang       #显示在浏览器上搜索的时候显示的标题
# header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
# email: You@gmail.com    
description: "你相信引力吗？"              #网站介绍
keyword: "御风姐姐，风迹，白日梦，叠翠山贵族" #关键词
url: "https://iloveaimer.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# 侧边栏 Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "诗酒趁年华"
sidebar-avatar:img/Gyro.jpg      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
weibo_username:     username
zhihu_username:     username
github_username:    username
facebook_username:  username

